language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [ -n "$GITHUB_COMPOSER_AUTH" ]; then composer config github-oauth.github.com ${GITHUB_COMPOSER_AUTH}; fi;
  - COMPOSER_ROOT_VERSION=`git describe --abbrev=0` composer install --no-interaction

script: bin/phpspec run
